# Generated by Django 4.2.15 on 2024-09-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "product", "verbose_name_plural": "products"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
