# Generated by Django 4.2.15 on 2024-09-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_options_alter_productcategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("Black", "Black"),
                    ("White", "White"),
                    ("Blue", "Blue"),
                    ("Brown", "Brown"),
                ],
                default="Blue",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
