# Generated by Django 4.2.15 on 2024-09-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="test",
            field=models.CharField(
                blank=True, default="null", max_length=10, null=True
            ),
        ),
    ]
