# Generated by Django 4.2.15 on 2024-09-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="test",
        ),
    ]
